In [1]:
import pandas as pd
import numpy as np
import geoenrich
from geoenrich import dataloader, enrichment, satellite, exports
import pathlib

pd.set_option('display.max_rows', 200)

In [2]:
df = pd.read_csv('../plankton_geoenrich_data/biodiv/plankton_med.csv')

In [4]:
variables = [
    'sst',
    'nh4_med',
    'no3_med',
    'po4_med',
    'o2_med',
    'chl_med',
    'thetao_med',
    'so_med',
    ]

In [5]:
df.shape

(62275, 96)

In [3]:
df = pd.read_csv('./plankton_data/planktons_med.csv')

In [4]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [5]:
# sort : 
df = df.sort_values(by=['datetime', 'lat', 'lon'])

In [8]:
taxons = [
    "Dinophysis acuminata",
    "Karenia mikimotoi",
    "Chaetoceros",
    "Dinophysis", 
    "Alexandrium minutum",
    "Pseudo-nitzschia"
]

In [9]:
df.head(30)

index                 taxon        lat       lon      value  \
33008  33008  Dinophysis acuminata  43.087319  5.906421        0.0   
30414  30414           Chaetoceros  43.382816  4.879229      100.0   
30415  30415  Dinophysis acuminata  43.382816  4.879229        0.0   
35172  35172  Dinophysis acuminata  42.134665  9.540678        0.0   
35173  35173     Karenia mikimotoi  42.134665  9.540678      100.0   
36633  36633  Dinophysis acuminata  42.076882  9.795849        0.0   
36634  36634     Karenia mikimotoi  42.076882  9.795849      100.0   
35174  35174           Chaetoceros  42.134665  9.540678      100.0   
35175  35175  Dinophysis acuminata  42.134665  9.540678        0.0   
35176  35176     Karenia mikimotoi  42.134665  9.540678      500.0   
30416  30416           Chaetoceros  43.382816  4.879229     3200.0   
30417  30417  Dinophysis acuminata  43.382816  4.879229        0.0   
33009  33009  Dinophysis acuminata  43.087319  5.906421        0.0   
30418  30418           Chaetoceros  43.382816  4.879229     1700.0   
30419  30419  Dinophysis acuminata  43.382816  4.879229        0.0   
30420  30420           Chaetoceros  43.382816  4.879229     2900.0   
30421  30421  Dinophysis acuminata  43.382816  4.879229        0.0   
33010  33010  Dinophysis acuminata  43.087319  5.906421        0.0   
33011  33011     Karenia mikimotoi  43.087319  5.906421     1500.0   
30422  30422           Chaetoceros  43.382816  4.879229     4000.0   
30423  30423  Dinophysis acuminata  43.382816  4.879229        0.0   
35177  35177  Dinophysis acuminata  42.134665  9.540678        0.0   
36635  36635  Dinophysis acuminata  42.076882  9.795849        0.0   
36636  36636     Karenia mikimotoi  42.076882  9.795849     1800.0   
32258  32258  Dinophysis acuminata  43.412986  5.163401        0.0   
16135  16135           Chaetoceros  43.434305  3.664537  2500000.0   
16136  16136  Dinophysis acuminata  43.434305  3.664537        0.0   
19301  19301  Dinophysis acuminata  43.377636  3.566870        0.0   
32259  32259  Dinophysis acuminata  43.412986  5.163401        0.0   
30424  30424           Chaetoceros  43.382816  4.879229     1200.0   

                   unit dataset            datetime subset  
33008  Nombre par litre     MED 1987-01-07 10:00:00    val  
30414  Nombre par litre     MED 1987-01-20 10:00:00    val  
30415  Nombre par litre     MED 1987-01-20 10:00:00    val  
35172  Nombre par litre     MED 1987-01-21 13:00:00    val  
35173  Nombre par litre     MED 1987-01-21 13:00:00    val  
36633  Nombre par litre     MED 1987-02-02 09:00:00    val  
36634  Nombre par litre     MED 1987-02-02 09:00:00    val  
35174  Nombre par litre     MED 1987-02-02 14:00:00    val  
35175  Nombre par litre     MED 1987-02-02 14:00:00    val  
35176  Nombre par litre     MED 1987-02-02 14:00:00    val  
30416  Nombre par litre     MED 1987-02-05 10:00:00    val  
30417  Nombre par litre     MED 1987-02-05 10:00:00    val  
33009  Nombre par litre     MED 1987-02-18 11:00:00    val  
30418  Nombre par litre     MED 1987-02-23 10:00:00    val  
30419  Nombre par litre     MED 1987-02-23 10:00:00    val  
30420  Nombre par litre     MED 1987-03-09 10:00:00    val  
30421  Nombre par litre     MED 1987-03-09 10:00:00    val  
33010  Nombre par litre     MED 1987-03-19 11:00:00    val  
33011  Nombre par litre     MED 1987-03-19 11:00:00    val  
30422  Nombre par litre     MED 1987-03-23 11:00:00    val  
30423  Nombre par litre     MED 1987-03-23 11:00:00    val  
35177  Nombre par litre     MED 1987-03-30 10:00:00    val  
36635  Nombre par litre     MED 1987-03-30 13:00:00    val  
36636  Nombre par litre     MED 1987-03-30 13:00:00    val  
32258  Nombre par litre     MED 1987-03-31 09:00:00    val  
16135  Nombre par litre     MED 1987-04-06 10:00:00  train  
16136  Nombre par litre     MED 1987-04-06 10:00:00  train  
19301  Nombre par litre     MED 1987-04-06 11:00:00  train  
32259  Nombre par litre     MED 1987-04-10 10:00:00    val  
30424 

In [10]:
index = df.groupby(['datetime', 'lat', 'lon']).apply(
    lambda rows: 
        np.array([[row["value"] if row["taxon"] == taxon else 0.0 for taxon in taxons]  for index, row in rows.iterrows()]).sum(axis=0)
)

In [11]:
# df2 like df but without rows : 
df2 = df.sort_values(by=['datetime', 'lat', 'lon']).drop_duplicates(subset=['datetime', 'lat', 'lon'])
df2 = df2.drop_duplicates(subset=['datetime', 'lat', 'lon'])

df2['taxons'] = index.values.tolist()


In [12]:
for taxon in taxons:
    df2[taxon] = df2['taxons'].apply(lambda x: x[taxons.index(taxon)])

In [14]:
df2.drop(columns=['taxon', 'taxons', 'value'], inplace=True)

In [16]:
df2.to_csv('./plankton_data/planktons_med_filtered.csv', index=False)

In [35]:
index_bool = index
for row in index_bool:
    for i in range(len(row)):
        if row[i] > 0:
            row[i] = 1
        else:
            row[i] = 0

In [40]:
index_sum = index_bool.apply(lambda row: row.sum())

In [44]:
index_sum.argmax()

5998

In [52]:
index_bool.index[5998]
# (Timestamp('2000-02-14 10:10:00'), 43.0873189621, 5.9064212393)

(Timestamp('2000-02-14 10:10:00'), 43.0873189621, 5.9064212393)

In [53]:
df[np.logical_and(df['datetime'] == '2000-02-14 10:10:00', np.logical_and(df['lat'] == 43.0873189621, df['lon'] == 5.9064212393))]

index                taxon        lat       lon    value  \
34048  34048  Alexandrium minutum  43.087319  5.906421    700.0   
34049  34049          Chaetoceros  43.087319  5.906421  64800.0   
34050  34050           Dinophysis  43.087319  5.906421    100.0   
34051  34051    Karenia mikimotoi  43.087319  5.906421   1900.0   
34052  34052     Pseudo-nitzschia  43.087319  5.906421  12500.0   

                   unit dataset            datetime subset  
34048  Nombre par litre     MED 2000-02-14 10:10:00    val  
34049  Nombre par litre     MED 2000-02-14 10:10:00    val  
34050  Nombre par litre     MED 2000-02-14 10:10:00    val  
34051  Nombre par litre     MED 2000-02-14 10:10:00    val  
34052  Nombre par litre     MED 2000-02-14 10:10:00    val

In [56]:
taxons = [
    "Dinophysis acuminata",
    "Karenia mikimotoi",
    "Chaetoceros",
    "Dinophysis", 
    "Alexandrium minutum",
    "Pseudo-nitzschia"
]

index[5998]

array([    0.,  1900., 64800.,   100.,   700., 12500.])

In [57]:
df

index                 taxon        lat       lon   value  \
33008  33008  Dinophysis acuminata  43.087319  5.906421     0.0   
30414  30414           Chaetoceros  43.382816  4.879229   100.0   
30415  30415  Dinophysis acuminata  43.382816  4.879229     0.0   
35172  35172  Dinophysis acuminata  42.134665  9.540678     0.0   
35173  35173     Karenia mikimotoi  42.134665  9.540678   100.0   
...      ...                   ...        ...       ...     ...   
44792  44792            Dinophysis  43.060336  3.075940     0.0   
58387  58387            Dinophysis  43.348598  4.694981     0.0   
59600  59600            Dinophysis  43.489290  5.122630   200.0   
49612  49612            Dinophysis  43.556311  4.035876   100.0   
40201  40201            Dinophysis  43.132711  3.137686  2100.0   

                   unit dataset            datetime subset  
33008  Nombre par litre     MED 1987-01-07 10:00:00    val  
30414  Nombre par litre     MED 1987-01-20 10:00:00    val  
30415  Nombre par litre     MED 1987-01-20 10:00:00    val  
35172  Nombre par litre     MED 1987-01-21 13:00:00    val  
35173  Nombre par litre     MED 1987-01-21 13:00:00    val  
...                 ...     ...                 ...    ...  
44792  Nombre par litre     MED 2021-12-27 13:20:00  train  
58387  Nombre par litre     MED 2021-12-27 13:20:00    val  
59600  Nombre par litre     MED 2021-12-27 15:15:00    val  
49612  Nombre par litre     MED 2021-12-28 09:10:00   test  
40201  Nombre par litre     MED 2021-12-28 10:40:00  train  

[62275 rows x 9 columns]

In [8]:
# Median of lon : 

df['lon'].median()
# subset : train for lon <= median, test for lon > median
df['subset'] = np.where(df['lon'] <= df['lon'].median(), 'train', 'test')

df.to_csv('./plankton_data/planktons_med.csv', index=False)

In [9]:
# at the right of the 80th percentile : val
perc_80 = df['lon'].quantile(0.8)

df.loc[df['lon'] > perc_80, 'subset'] = 'val'

In [10]:
df.to_csv('./plankton_data/planktons_med.csv', index=False)

In [5]:
# output = exports.retrieve_data("plankton", 3897, 'oxygen', shape = 'buffer')
# values = exports.export_to_array(output)

# exports.collate_npy(ds_ref = 'plankton_med', data_path = './npy', slice = (0, 10000))

In [11]:
raster = np.load('./npy/plankton_med-npy/193.npy')

In [12]:
raster[:,:,0]

array([[         nan,          nan,          nan, ..., 297.44924927,
        297.58990479, 297.63739014],
       [         nan,          nan,          nan, ..., 297.29650879,
        297.39498901, 297.40649414],
       [         nan,          nan,          nan, ..., 297.19326782,
        297.22668457, 297.18890381],
       ...,
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan]])

In [13]:
raster[:,:,6]

array([[        nan,         nan,         nan, ..., 23.96222496,
        24.19167137, 24.26071167],
       [        nan,         nan,         nan, ..., 23.64068794,
        23.89012718, 23.97191238],
       [        nan,         nan,         nan, ..., 23.58297157,
        23.71512794, 23.69724846],
       ...,
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [3]:
import numpy as np
arr = np.load('/mounts/Datasets4/DeepOcean/npy-norm/gbif_10779164-norm-npy/1020055146.npy')